ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port:  ${PORT}

postgres:
  url: "jdbc:postgresql://ep-super-paper-a8i6y8km-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
  user: "neondb_owner"
  password: "npg_B4hpmN0tFibW"
